### ISSUE TITLE
template import issue

### ISSUE THREAD

**Issue by ice-8** [jasonmcintosh/rabbitmq-zabbix#19]
hi. i've tried to import template into zabbix-2.0 and got the error:
```
mb_strlen() expects parameter 1 to be string, array given [include/func.inc.php:831]
mysql_real_escape_string() expects parameter 1 to be string, array given [include/db.inc.php:646]
Array to string conversion [include/classes/db/DB.php:408]
Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authpassphrase,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('rabbitmq queues','7','','','360','0','','0','','','','','','0','','','','','',Array,'1','','rabbitmq.discovery_queue','','10144','1','4','0',NULL,'27071')] [Unknown column 'Array' in 'field list']
```

did i do something wrong? could you please guess why it has happened?

**Comment by jasonmcintosh** [comment]
Well two guesses - one is that all my testing has been done on zabbix 2.2 or newer.  I've not tried 2.4 but I've heard successes on that.  Another possibility is that the latest version of the template I committed has a few bugs - haven't had a chance to work on them yet though.  You might try the prior release and see if that works for you.

**Comment by jasonmcintosh** [comment]
I HOPEFULLY fixed the latest release of the template with a few of my tops.  Note, that probably won't help if you're running zabbix 2.0 and it's a version issue with that version.  I'm also not seeing anything called "Array" in the templates - off hand I'd GUESS that it's a bug on your zabbix version.  What you can do is try exporting a template and compare the items and discovery rules to see if I have an item your version doens't support.

**Comment by jasonmcintosh** [comment]
Closing this as I've not heard anything recently.  If you hit more problems, feel free to re-open.

**Comment by ice-8** [comment]
Hi, sorry for delay. I've updated zabbix-server to 2.2 and still getting error when import template:
```
mb_strlen() expects parameter 1 to be string, array given [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DB::checkValueTypes() → zbx_strlen() → mb_strlen() in /usr/share/zabbix/include/func.inc.php:955]
mysqli_real_escape_string() expects parameter 2 to be string, array given [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DB::checkValueTypes() → zbx_dbstr() → mysqli_real_escape_string() in /usr/share/zabbix/include/db.inc.php:1224]
Array to string conversion [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → implode() in /usr/share/zabbix/include/classes/db/DB.php:450]
Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('rabbitmq queues','7','','','360','0','','','0','0','','0','','','','','0','','','','','',Array,'1','','rabbitmq.discovery_queue','','10146','1','4','0',NULL,'27214')] [Unknown column 'Array' in 'field list']
```

**Comment by ice-8** [comment]
oh, i'm very sorry. i downloaded master branch zip-archive before.
2.0.1 release imported successful.
